In [1]:
from scipy.stats import ks_2samp

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10)
arr2=np.arange(10)

In [4]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
res = ks_2samp(arr1,arr2)

In [7]:
round(res.pvalue)

1

In [ ]:
Null: Two datset are from same distribution

Alterate: Two dataset are not from same distribution


if p>=0.05 :
    We have sufficent proof that null hypothesis is True
else:
    We don't have sufficient proof that null hypothesis is True

In [8]:
res= ks_2samp(arr1,arr2)
round(res.pvalue,3)

1.0

In [11]:
arr2=np.arange(10,20)

In [12]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
res = ks_2samp(arr1,arr2)

In [14]:
round(res.pvalue)

0